apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-sensitive-app
  labels:
    app: latency-sensitive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: latency-sensitive
  template:
    metadata:
      labels:
        app: latency-sensitive
    spec:
      containers:
      - name: app
        image: jhlin0925/benchmark-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_TYPE
          value: "latency-sensitive"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-limit-app
  labels:
    app: energy-limit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energy-limit
  template:
    metadata:
      labels:
        app: energy-limit
    spec:
      containers:
      - name: app
        image: jhlin0925/benchmark-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_TYPE
          value: "energy-limit"
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-limit-app
  labels:
    app: resource-limit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-limit
  template:
    metadata:
      labels:
        app: resource-limit
    spec:
      containers:
      - name: app
        image: jhlin0925/benchmark-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_TYPE
          value: "resource-limit"
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
