apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: benchmark-service-monitor
  namespace: monitoring
  labels:
    release: my-kube-prom-stack
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - latency-sensitive-app
          - energy-limit-app
          - resource-limit-app

  namespaceSelector:
    matchNames:
      - default  # 假設三個 apps 都在 default namespace

  endpoints:
    - port: http  # 確保 Service 的 port.name 是 "http"
      path: /metrics
      interval: 15s
